Expose weak versions of CAS methods
mvdnes/spin-rs pull request #150
Opened 2023-04-12 12:48 UTC by tsoutsman

Hi,

I'm working on implementing sync primitives in [Theseus OS](https://github.com/theseus-os/Theseus) on top of spin locks. We currently [have to implement our own spin lock](https://github.com/theseus-os/Theseus/blob/cb77432051dde0caf7fcf7eb4c04fa231916f624/libs/sync/src/mutex.rs#L146-L281) that is identical to `spin` except that it exposes `try_lock_weak`, so that we can have custom `lock` implementations that use a weak CMPXCHG, while still using a strong CMPXCHG for `try_lock`.

It would be nice if we could upstream this so that we could directly depend on `spin`. I think it makes sense to include it as `spin` is often used to build higher-level primitives which could use a weak CMPXCHG for better performance.

2023-04-12 13:01 UTC, zesterer requested changes
Thanks, these changes look good to me. Just a few minor comments. I'm happy to expose this API though.

2023-04-12 13:08 UTC, tsoutsman commented on src/mutex/spin.rs
> +        };
Should I make `strong` a const generic, or would that break some minimum supported rust version?

2023-04-12 13:16 UTC, tsoutsman commented on src/mutex/spin.rs
> +        };
Actually, I may as well just remove `try_lock_internal` then.

2023-04-12 16:44 UTC, zesterer commented on src/mutex/spin.rs
> +        };
Thanks, I think that's for the best for now. I believe a const generic would break MSRV, sadly :(

2023-04-12 17:08 UTC, merged

2023-04-12 17:08 UTC, zesterer commented
Are you looking to see a new release with this feature?

2023-04-13 00:00 UTC, tsoutsman commented
It would be nice but not critical. We're happy to just use a patch manifest section.

2023-04-13 01:06 UTC, tsoutsman commented
Sorry, I'm currently implementing our blocking spin lock and noticed there isn't a way to access the reader count from the guard.

Ideally, `force_read_decrement` would return the previous count so that we know when no readers are left. However, this would be a breaking change and require exposing `rw_lock::READER`, which is an implementation detail, so I think it may be better if we forked `spin` rather than upstreaming that change, considering how niche our use case is and how many dependents `spin` has.