barrier implementation
mvdnes/spin-rs pull request #61
Opened 2019-01-16 03:14 UTC by JoshMcguigan

closes #28 

I'm not sure if there is interest in this, but I saw the issue and wanted to give it a shot. The implementation borrows heavily from the standard library, so I left their copyright notice in. I'm not sure of the proper mechanism for handling that. 

The examples still use stdlib, but I can write up other examples if there is interest in merging this. 

Also, I suspect there might be a more performant way to pull this off, so I'd appreciate feedback there. 

Thanks!

2019-01-16 15:01 UTC, Ericson2314 commented on src/barrier.rs
> +        while local_gen == lock.generation_id &&
Well there's still incrementing the generation, but that's condition can be optimized away by the compiler by turning that bool into 0 or 1 and always incrementing.

2019-01-17 02:48 UTC, JoshMcguigan commented
Thank you for the feedback. Let me know if you see any other issues, and I'd be happy to correct.

2020-10-10 12:54 UTC, zesterer commented
Hello. I'm now helping to maintain this project. Is this still something that you're interested in getting added?

2020-10-10 15:05 UTC, JoshMcguigan commented
Hi, thanks for following up. I never had a direct need for this, so I'm not opposed to this PR being closed if you don't want to bring in this implementation. On the other hand I'm happy to do more cleanup if you have comments and would like to see this merged.

2020-10-10 15:51 UTC, zesterer requested changes
Hey, I've just done a brief review. On the whole the implementation looks great, just a few minor nit-picks / questions. Once these are addressed I'll happily merge!

2020-10-10 15:51 UTC, zesterer commented on src/barrier.rs
> +/// A barrier enables multiple threads to synchronize the beginning
Could this be changed to something akin to "A primitive that synchronizes the execution of multiple threads" to be consistent with other such short descriptions in the crate?

2020-10-10 15:51 UTC, zesterer commented on src/barrier.rs
> +/// # Examples
Just a single `Example` here

2020-10-10 15:51 UTC, zesterer commented on src/barrier.rs
> +    pub const fn new(n: usize) -> Barrier {
Is the behaviour of `n = 0` specified? I think the implementation just performs the same behaviour as `n = 1` but we might want to either define this behaviour as unspecified (but not unsound) or define it.

2020-10-11 17:49 UTC, JoshMcguigan commented
Thanks for the review. I think I've addressed your comments, and I've rebased this.

2020-10-12 00:01 UTC, zesterer commented
@JoshMcguigan Thanks for the brilliant work! Unfortunately a previous MR was just merged so there is a conflict. It should only be a single line though.

2020-10-12 00:01 UTC, zesterer approved these changes

2020-10-18 16:13 UTC, JoshMcguigan commented
I've rebased to resolve the merge conflict.

2020-10-18 22:10 UTC, zesterer commented
Thanks very much for working on this! I think this completes the 0.7 release.

2020-10-18 22:10 UTC, merged